{ config, lib, pkgs, ... }:

let
  cfg = config.programs.exwm-vr;

  # Convert a Nix attrset to Elisp setq expressions
  nixToElisp = attrs:
    let
      convert = name: value:
        let
          elispName = builtins.replaceStrings [ "_" ] [ "-" ] name;
          elispValue =
            if builtins.isBool value then (if value then "t" else "nil")
            else if builtins.isInt value then toString value
            else if builtins.isFloat value then toString value
            else if builtins.isString value then ''"${value}"''
            else if builtins.isList value then
              "'(${builtins.concatStringsSep " " (map (v:
                if builtins.isString v then ''"${v}"''
                else toString v
              ) value)})"
            else throw "Unsupported type for Elisp conversion: ${name}";
        in
        "(setq ${elispName} ${elispValue})";
    in
    builtins.concatStringsSep "\n" (lib.mapAttrsToList convert attrs);

  # Generate Qutebrowser theme from Emacs theme name
  qutebrowserTheme = theme:
    let
      themes = {
        "modus-vivendi" = {
          bg = "#000000";
          fg = "#ffffff";
          accent = "#79a8ff";
          sel-bg = "#3f3f3f";
          sel-fg = "#ffffff";
          warn = "#fec43f";
          error = "#ff5f59";
        };
        "modus-operandi" = {
          bg = "#ffffff";
          fg = "#000000";
          accent = "#0031a9";
          sel-bg = "#c4c4c4";
          sel-fg = "#000000";
          warn = "#813e00";
          error = "#a60000";
        };
        "ef-autumn" = {
          bg = "#0f0e06";
          fg = "#cfbcba";
          accent = "#efa040";
          sel-bg = "#3a2a0a";
          sel-fg = "#cfbcba";
          warn = "#d0a020";
          error = "#ff7a5f";
        };
      };
      colors = themes.${theme} or themes."modus-vivendi";
    in ''
      # EXWM-VR Qutebrowser theme — generated from Emacs theme: ${theme}
      # Do not edit manually; managed by home-manager.

      c.colors.completion.fg = "${colors.fg}"
      c.colors.completion.odd.bg = "${colors.bg}"
      c.colors.completion.even.bg = "${colors.bg}"
      c.colors.completion.category.fg = "${colors.accent}"
      c.colors.completion.category.bg = "${colors.bg}"
      c.colors.completion.item.selected.fg = "${colors.sel-fg}"
      c.colors.completion.item.selected.bg = "${colors.sel-bg}"
      c.colors.statusbar.normal.fg = "${colors.fg}"
      c.colors.statusbar.normal.bg = "${colors.bg}"
      c.colors.statusbar.command.fg = "${colors.fg}"
      c.colors.statusbar.command.bg = "${colors.bg}"
      c.colors.tabs.bar.bg = "${colors.bg}"
      c.colors.tabs.odd.fg = "${colors.fg}"
      c.colors.tabs.odd.bg = "${colors.bg}"
      c.colors.tabs.even.fg = "${colors.fg}"
      c.colors.tabs.even.bg = "${colors.bg}"
      c.colors.tabs.selected.odd.fg = "${colors.sel-fg}"
      c.colors.tabs.selected.odd.bg = "${colors.sel-bg}"
      c.colors.tabs.selected.even.fg = "${colors.sel-fg}"
      c.colors.tabs.selected.even.bg = "${colors.sel-bg}"
      c.colors.hints.fg = "${colors.bg}"
      c.colors.hints.bg = "${colors.accent}"
      c.colors.messages.error.fg = "${colors.fg}"
      c.colors.messages.error.bg = "${colors.error}"
      c.colors.messages.warning.fg = "${colors.fg}"
      c.colors.messages.warning.bg = "${colors.warn}"
    '';

  configEl = ''
    ;;; exwm-vr-config.el --- Generated EXWM-VR configuration  -*- lexical-binding: t; -*-
    ;; Generated by home-manager. Do not edit manually.

    ${nixToElisp cfg.config}

    ${lib.optionalString cfg.keepassxc.enable ''
    (setq ewwm-keepassxc-enable t)
    (setq ewwm-keepassxc-database-path "${cfg.keepassxc.databasePath}")
    ''}

    ${lib.optionalString (cfg.winkCalibration != null) ''
    (setq ewwm-vr-wink-calibration-file "${cfg.winkCalibration}")
    ''}

    (setq ewwm-vr-gaze-zone-layout "${cfg.gazeZoneLayout}")

    (provide 'exwm-vr-config)
    ;;; exwm-vr-config.el ends here
  '';

in {
  options.programs.exwm-vr = {
    enable = lib.mkEnableOption "EXWM-VR user configuration";

    config = lib.mkOption {
      type = lib.types.attrsOf (lib.types.oneOf [
        lib.types.bool
        lib.types.int
        lib.types.float
        lib.types.str
        (lib.types.listOf lib.types.str)
      ]);
      default = { };
      description = ''
        Attribute set of EXWM-VR configuration variables.
        Keys are converted from snake_case to kebab-case for Elisp.
        Values are converted: bool -> t/nil, string -> "string", int -> int.
        Generates setq forms in ~/.config/exwm-vr/config.el.
      '';
      example = lib.literalExpression ''
        {
          ewwm_floating_border_width = 2;
          ewwm_workspace_number = 4;
          ewwm_vr_enable = true;
        }
      '';
    };

    winkCalibration = lib.mkOption {
      type = lib.types.nullOr lib.types.path;
      default = null;
      description = "Path to wink calibration JSON file.";
    };

    gazeZoneLayout = lib.mkOption {
      type = lib.types.enum [ "default" "compact" "wide" "minimal" ];
      default = "default";
      description = "Gaze zone layout preset.";
    };

    keepassxc = {
      enable = lib.mkEnableOption "KeePassXC integration";
      databasePath = lib.mkOption {
        type = lib.types.str;
        default = "~/Passwords.kdbx";
        description = "Path to KeePassXC database file.";
      };
    };

    theme = lib.mkOption {
      type = lib.types.enum [ "modus-vivendi" "modus-operandi" "ef-autumn" ];
      default = "modus-vivendi";
      description = ''
        Emacs theme name. Also generates a matching Qutebrowser color scheme.
      '';
    };

    configDir = lib.mkOption {
      type = lib.types.str;
      default = "${config.xdg.configHome}/exwm-vr";
      description = "EXWM-VR configuration directory.";
    };

    # --- Compositor options ---

    compositor = {
      package = lib.mkOption {
        type = lib.types.nullOr lib.types.package;
        default = null;
        description = "Compositor package (ewwm-compositor binary).";
      };

      extraArgs = lib.mkOption {
        type = lib.types.listOf lib.types.str;
        default = [ ];
        description = "Extra command-line arguments for the compositor.";
        example = [ "--headless" "--backend" "drm" ];
      };
    };

    # --- Emacs options ---

    emacs = {
      package = lib.mkOption {
        type = lib.types.package;
        default = pkgs.emacs-pgtk or pkgs.emacs;
        defaultText = lib.literalExpression "pkgs.emacs-pgtk";
        description = "Emacs package to use.";
      };
    };

    # --- Elisp package (load-path) ---

    elisp = {
      package = lib.mkOption {
        type = lib.types.nullOr lib.types.package;
        default = null;
        description = ''
          ewwm-elisp store path for load-path.
          Set to the flake's packages.ewwm-elisp output.
        '';
      };
    };

    # --- Systemd user services ---

    systemd = {
      enable = lib.mkOption {
        type = lib.types.bool;
        default = false;
        description = ''
          Generate systemd user services for compositor and Emacs.
          Useful for non-NixOS hosts (e.g. Rocky Linux with Nix).
          home-manager switch will install the services.
        '';
      };
    };
  };

  config = lib.mkIf cfg.enable (lib.mkMerge [
    # Always: generate config.el, qutebrowser theme, env vars, portal config
    {
      xdg.configFile."exwm-vr/config.el".text = configEl;
      xdg.configFile."qutebrowser/exwm-vr-theme.py".text = qutebrowserTheme cfg.theme;

      # Portal backend config for screen sharing, file chooser, etc.
      xdg.configFile."xdg-desktop-portal/exwm-vr-portals.conf".text = ''
        [preferred]
        default=gtk
        org.freedesktop.impl.portal.ScreenCast=wlr
        org.freedesktop.impl.portal.Screenshot=wlr
        org.freedesktop.impl.portal.Inhibit=none
      '';

      home.sessionVariables = {
        EXWM_VR_CONFIG_DIR = cfg.configDir;
        XDG_CURRENT_DESKTOP = "EXWM-VR";
        XDG_SESSION_TYPE = "wayland";
        QT_QPA_PLATFORM = "wayland";
        MOZ_ENABLE_WAYLAND = "1";
        _JAVA_AWT_WM_NONREPARENTING = "1";
        GDK_BACKEND = "wayland,x11";
        SDL_VIDEODRIVER = "wayland";
        XCURSOR_THEME = "Adwaita";
        XCURSOR_SIZE = "24";
      };
    }

    # Systemd user services (for non-NixOS hosts like Rocky)
    (lib.mkIf cfg.systemd.enable (
      let
        compositorBin = "${cfg.compositor.package}/bin/ewwm-compositor";
        compositorArgs = lib.concatStringsSep " " cfg.compositor.extraArgs;
        elispLoadPath =
          if cfg.elisp.package != null then
            lib.concatStringsSep ":" [
              "${cfg.elisp.package}/share/emacs/site-lisp/ewwm/core"
              "${cfg.elisp.package}/share/emacs/site-lisp/ewwm/vr"
              "${cfg.elisp.package}/share/emacs/site-lisp/ewwm/ext"
            ]
          else "";
        emacsLoadFlags =
          if cfg.elisp.package != null then
            "-L ${cfg.elisp.package}/share/emacs/site-lisp/ewwm/core "
            + "-L ${cfg.elisp.package}/share/emacs/site-lisp/ewwm/vr "
            + "-L ${cfg.elisp.package}/share/emacs/site-lisp/ewwm/ext"
          else "";
      in {
        assertions = [
          {
            assertion = cfg.compositor.package != null;
            message = "programs.exwm-vr.systemd.enable requires compositor.package to be set.";
          }
        ];

        systemd.user.services.ewwm-compositor = {
          Unit = {
            Description = "EWWM Wayland Compositor";
            Documentation = "https://github.com/Jesssullivan/XoxdWM";
            ConditionEnvironment = "WAYLAND_DISPLAY";
          };
          Service = {
            ExecStart = "${compositorBin} ${compositorArgs}";
            Restart = "on-failure";
            RestartSec = 2;
            Environment = [
              "XDG_RUNTIME_DIR=%t"
            ];
          };
          Install = {
            WantedBy = [ "ewwm-session.target" ];
          };
        };

        systemd.user.services.ewwm-emacs = {
          Unit = {
            Description = "EWWM Emacs Daemon";
            Documentation = "https://github.com/Jesssullivan/XoxdWM";
            After = [ "ewwm-compositor.service" ];
            Requires = [ "ewwm-compositor.service" ];
          };
          Service = {
            ExecStart = "${cfg.emacs.package}/bin/emacs --daemon ${emacsLoadFlags}"
              + lib.optionalString (cfg.elisp.package != null)
                " -l ${cfg.configDir}/config.el";
            Restart = "on-failure";
            RestartSec = 3;
            Environment = [
              "XDG_RUNTIME_DIR=%t"
            ] ++ lib.optional (elispLoadPath != "")
              "EMACSLOADPATH=${elispLoadPath}:";
          };
          Install = {
            WantedBy = [ "ewwm-session.target" ];
          };
        };

        systemd.user.targets.ewwm-session = {
          Unit = {
            Description = "EWWM Session";
            Documentation = "https://github.com/Jesssullivan/XoxdWM";
            Wants = [ "ewwm-compositor.service" "ewwm-emacs.service" ];
          };
          Install = {
            WantedBy = [ "graphical-session.target" ];
          };
        };
      }
    ))
  ]);
}
